// Auto generated amalgamated source.
#include "/Users/rosethomas/ambiosDSP/visage/visage_graphics/canvas.cpp"
#include "/Users/rosethomas/ambiosDSP/visage/visage_graphics/color.cpp"
#include "/Users/rosethomas/ambiosDSP/visage/visage_graphics/font.cpp"
#include "/Users/rosethomas/ambiosDSP/visage/visage_graphics/gradient.cpp"
#include "/Users/rosethomas/ambiosDSP/visage/visage_graphics/graphics_caches.cpp"
#include "/Users/rosethomas/ambiosDSP/visage/visage_graphics/graphics_utils.cpp"
#include "/Users/rosethomas/ambiosDSP/visage/visage_graphics/image.cpp"
#include "/Users/rosethomas/ambiosDSP/visage/visage_graphics/layer.cpp"
#include "/Users/rosethomas/ambiosDSP/visage/visage_graphics/palette.cpp"
#include "/Users/rosethomas/ambiosDSP/visage/visage_graphics/post_effects.cpp"
#include "/Users/rosethomas/ambiosDSP/visage/visage_graphics/region.cpp"
#include "/Users/rosethomas/ambiosDSP/visage/visage_graphics/renderer.cpp"
#include "/Users/rosethomas/ambiosDSP/visage/visage_graphics/screenshot.cpp"
#include "/Users/rosethomas/ambiosDSP/visage/visage_graphics/shape_batcher.cpp"
#include "/Users/rosethomas/ambiosDSP/visage/visage_graphics/shapes.cpp"
#include "macos/emoji_macos.cpp"
